### PR TITLE
3 more commits for the backport

### PR DESCRIPTION
**Pull request by lholmquist**
the 3 remaining commits as noted in https://github.com/cloudevents/sdk-javascript/pull/336#issue-478882247

### CODE REVIEW

**Comment by lance** [comment]
@lholmquist I didn't see this until I had already pushed those changes to `origin/v3.2.x-backport`. Thanks for keeping me on it though!

**Comment by lance** [comment]
But oops! I shouldn't have pushed to `origin`. My bad.

**Comment by lance** [comment]
Uhh and I still screwed the pooch by squashing all three. I am going to fix this now.

**Comment by lholmquist** [comment]
lol   :facepalm:

**Pull request merged**
